
import { library } from '@fortawesome/fontawesome-svg-core'
import { 
  faTrashAlt, 
  faFile, 
  faFileImage, 
  faEdit, 
  faCheck, 
  faClock, 
  faArrowUp, 
  faArrowDown, 
  faMinusCircle,
  faCheckCircle,
  faStickyNote,
  faTimes,
  faUserLock,
  faPaperPlane,
  faUserTimes,
  faBold,
  faItalic,
  faStrikethrough,
  faUnderline,
  faCode,
  faParagraph,
  faListUl,
  faListOl,
  faQuoteRight,
  faRulerHorizontal,
  faGripHorizontal,
  faUndo,
  faRedo,
  faLink
 } from '@fortawesome/free-solid-svg-icons'

library.add(faTrashAlt)
library.add(faFileImage)
library.add(faFile)
library.add(faEdit)
library.add(faCheck)
library.add(faClock)
library.add(faArrowUp)
library.add(faArrowDown)
library.add(faMinusCircle)
library.add(faCheckCircle)
library.add(faStickyNote)
library.add(faTimes)
library.add(faUserLock)
library.add(faPaperPlane)
library.add(faUserTimes)
library.add(faBold)
library.add(faItalic)
library.add(faStrikethrough)
library.add(faUnderline)
library.add(faCode)
library.add(faParagraph)
library.add(faListUl)
library.add(faListOl)
library.add(faQuoteRight)
library.add(faRulerHorizontal)
library.add(faGripHorizontal)
library.add(faUndo)
library.add(faRedo)
library.add(faLink)